tools:
  php_mess_detector:
    extensions:
      - php
      - inc
  php_code_sniffer:
    config:
      standard: Drupal
    extensions:
      - php
      - inc
  php_cpd:
    names:
      - '*.php'
      - '*.inc'
  php_loc:
    names:
      1: '*.inc'
      2: '*.php'
  php_pdepend:
    suffixes:
      - php
      - inc
  external_code_coverage:
    # Wait up to fifteen minutes for code coverage.
    timeout: 900
before_commands:
  # Remove vendor code, we don't want to analyze that.
  - rm -rf vendor
