# Configuration for Travis CI at http://travis-ci.org/#!/xendk/bandaid

language: php

php:
  - 5.3
  - 5.4

env:
  - UNISH_DB_URL=mysql://root:@127.0.0.1 DRUSH_VERSION=7.0.0 COVERAGE=y UNISH_NO_TIMEOUTS=y
  - UNISH_DB_URL=mysql://root:@127.0.0.1 DRUSH_VERSION=6.6.0

# matrix:
#   exclude:
#     - php: 5.3
#     - env: UNISH_DB_URL=mysql://root:@127.0.0.1 DRUSH_VERSION=master COVERAGE=y UNISH_NO_TIMEOUTS=y
      
install:
  # We have to checkout drush and run composer install, rather than
  # using composer global require, as the autoload-dev to load the
  # test base classes is only added for root projects.
  - composer self-update
  - export PATH="$HOME/drush:$PATH"
  - export DRUSH_DIR=~/drush
  - git clone https://github.com/drush-ops/drush.git $DRUSH_DIR
  - cd $DRUSH_DIR 
  - git checkout $DRUSH_VERSION
  # Install Drush dependencies.
  - composer install --prefer-source
  - phpenv rehash
  - cd -
  # Install our dependencies.
  - composer install --prefer-source
  - if ( test ! -z $COVERAGE ); then mkdir cov; fi
  - if ( test ! -z $COVERAGE ); then export COVERAGE=--coverage-clover=`pwd`/cov/clover.xml; fi
before_script:
  - if ( test $DRUSH_VERSION = 7.0.0 ); then export CONFIG="--bootstrap=$DRUSH_DIR/tests/bootstrap.inc" ; else export CONFIG="--bootstrap=$DRUSH_DIR/tests/drush_testcase.inc"; fi
  # Disable host key checking for d.o.
  - echo -e "Host git.drupal.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script: phpunit $CONFIG $COVERAGE tests

notifications:
  flowdock: 78b17a3314f1bac5207d8e65e391287b

after_script:
  - if ( test ! -z $COVERAGE ); then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if ( test ! -z $COVERAGE ); then php ocular.phar code-coverage:upload --format=php-clover cov/clover.xml; fi
